services:
  - type: web
    name: diabetes-prediction-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python check_models.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: PYTHONPATH
        value: . 